{{- if and .Values.enableStandaloneCompactors .Values.compactor.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "quickwit.fullname" . }}-compactor
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
    app.kubernetes.io/component: compactor-hpa
  {{- with .Values.compactor.autoscaling.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "quickwit.fullname" . }}-compactor
  minReplicas: {{ .Values.compactor.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.compactor.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.compactor.autoscaling.metrics | nindent 4 }}
  {{- if .Values.compactor.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.compactor.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
