{{- $config := deepCopy .Values.config -}}
{{- if .Values.metastore_ro.enabled -}}
{{- $searcherConfig := $config.searcher | default dict -}}
{{- $_ := set $searcherConfig "use_metastore_read_replica" true -}}
{{- $_ := set $config "searcher" $searcherConfig -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quickwit.fullname" . }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
data:
  node.yaml: |-
    {{- toYaml $config | nindent 4 }}
