{{- if .Values.httproute.enabled -}}
{{- $fullname := include "quickwit.fullname" . }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullname }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
    {{- with .Values.httproute.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httproute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.httproute.rules }}
    - matches:
      {{- with .matches }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .backendRefs }}
      backendRefs:
        {{- range .backendRefs }}
        - group: {{ .group | default "" | quote }}
          kind: {{ .kind | default "Service" | quote }}
          {{- if eq (.kind | default "Service") "Service" }}
          name: {{ $fullname }}-{{ .name | default "searcher" }}
          {{- else }}
          name: {{ .name }}
          {{- end }}
          port: {{ .port }}
          {{- if .weight }}
          weight: {{ .weight }}
          {{- end }}
        {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
