{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quickwit.serviceAccountName" . }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
